version: 2
builds:
  - main: ./cmd/docker-machine-driver-hetzner
    binary: docker-machine-driver-hetzner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto
