version: 2
builds:
  - main: ./cmd/docker-machine-driver-hetzner
    binary: docker-machine-driver-hetzner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto

changelog:
  sort: asc
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: "📖 Documentation"
      regexp: '^.*?docs(\(.+\))?\!?:.+$'
      order: 2
    - title: "🔧 CI/CD & Maintenance"
      regexp: '^.*?(ci|chore|build|refactor)(\(.+\))?\!?:.+$'
      order: 3
    - title: "Other"
      order: 999
  filters:
    exclude:
      - '^Merge '
